services:
  thor:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.thor.rule=Host(`thorpersonal.com.br`)"
      - "traefik.http.routers.thor.entrypoints=websecure"
      - "traefik.http.routers.thor.tls=true"
      - "traefik.http.routers.thor.tls.certresolver=letsencrypt"
      - "traefik.http.services.thor.loadbalancer.server.port=5173"      
    restart: unless-stopped

networks:
  traefik_proxy:
    external: true

